### ISSUE TITLE
Validacion del campo sala (combo box)

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#1]
Tipo= Error, mejora
Descripción= No contiene información por parte del backend listado y muestra de información en el frontend
Pasos a reproducir
        1.-Ingreso al login de inicio link: http: //localhost:5173/login
        2.-Click en el apartado de turnos link: http://localhost:5173/shifts 
        3.-Click en nuevo para crear turno link: http://localhost:5173/shifts/create
        4.-Asignacion del combo box el listado se encuentra en blanco
![image](https://github.com/user-attachments/assets/d3dcbda8-68d2-4f6d-a730-62cb0aeeb138)

![image](https://github.com/user-attachments/assets/c952c6df-c3e9-4e2c-8dc4-6538e0c82f58)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/de80fe0b-d0ee-463e-b65a-066bc6ad8019)
10 DE NOVIEMBRE DE 2024
