### ISSUE TITLE
Validación en descuentos 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#10]
Tipo= Error, mejora
Descripción= Los nombres de descuento tiene que ser letras no con numeros 
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de turnos http://localhost:5173/discounts
3.-Click en nuevo para crear turno link: http://localhost:5173/discounts/create
4.-Asignar informacion en los campos para verificar solo letras, aun crea el descuento 

![image](https://github.com/user-attachments/assets/65e0654b-b997-45bd-9755-1e4bb521b0ba)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/bb037031-1940-4b96-ae91-9f7ebbabd6a8)
10 DE NOVIEMBRE DE 2024
