### ISSUE TITLE
Registrar inscripciones

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#11]
Tipo= Error, mejora,incidente
Descripción= No se asignar los datos para la inscripcion y de esta manera no se inscriben los estudiantes con los datos seleccionados 
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de inscripciones http://localhost:5173/enrollments
3.-Click en nuevo para crear inscripciones http://localhost:5173/enrollments/create
4.-En el apartado de crear un estudiante no me permite inscribir al estudianete que se sale un error

![image](https://github.com/user-attachments/assets/4066ae91-b306-4ca9-aff4-ee0b9d252ac7)
![image](https://github.com/user-attachments/assets/072ee04a-c613-40bd-a762-be864d814751)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO (EN REVISIÓN)
![image](https://github.com/user-attachments/assets/d40559d3-5098-45aa-ba67-2a239ad94ad8)
![image](https://github.com/user-attachments/assets/39ab7fd6-1484-4f68-88f0-f323649c99b2)
