### ISSUE TITLE
BOTÓN DE VOLVER QUE CIERRA SESIÓN

### ISSUE THREAD

**Issue by xXMamboxXx** [mirandaniel17/itc-backend#12]
Tipo= Error
Descripción= Al estar en una página inexistente el botón de volver vuelve al login, lo que impide volver a la sesión
1.-Buscar una página inexistente: http: //localhost:5173/test
2.-Click en el botón de Volver
![image](https://github.com/user-attachments/assets/f340fc9f-2d40-4489-baa9-a2ad53efc191)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/3a218ee5-6919-4ed0-8479-487d7c2e635c)
