### ISSUE TITLE
Modificacion de permisos

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#13]
Descripción= al registro de un nuevo usuario este puede a si mismo modificarse los permisos y con eso lleva a una gestion no eficiente
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de inscripciones http://localhost:5173/profile
3.-En el apartado para modificar los permisos se muestra y puede darse privilegios mas altos
![image](https://github.com/user-attachments/assets/65bfd013-b725-456e-a525-57df35f0b88a)
![image](https://github.com/user-attachments/assets/0c98b953-9d7e-45bd-8d01-9a0c29c2b4ec)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/f39015c0-d47d-425b-b8aa-9f4b66a911b5)
![image](https://github.com/user-attachments/assets/c7422b80-1d96-43a9-bd4f-e336c1c5b735)
