### ISSUE TITLE
Registro de correo electronico

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#14]
Descripcion: error al momento de registra los correos electronicos estos no tiene que tenes caracteres especial al inicio ni la final es decir no puede comenzar con (.) o terminar en (.) o algun caracter tiene que iniciar con letras y tener ., !, #, $, %, &, ', *, +, -, /, =, ?, ^, _, `, {, |, }, ~ estos caracteres especiales internamente como letras mayusculas y minusculas, como numeros del 0-9
Pasos:
1.- iniciar en el host http://localhost:5173/register
2.- Ingresar los datos con caracteres no valido 
3.- Poner registrar el nuevo usuario este se registra 
![image](https://github.com/user-attachments/assets/3d23aa98-73ca-48de-96a1-572b3d56a719)
![image](https://github.com/user-attachments/assets/61fbd5b8-7bbf-49f1-a084-a8ae3e73c05d)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/427a200c-bf7c-45a5-a73a-1aa476b4f1f5)
10 DE NOVIEMBRE DE 2024
