### ISSUE TITLE
Recuerdo de registros previos 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#15]
Descripción: Al momento de registrar los datos para iniciar sesión se tiene un boton de recuerdame el cual no efectua su funcionalidad respectiva, de acuerdo a esto no tendría  guardar el registro del inicio de sesion
Pasos a Seguir:
1.- ingresar a http://localhost:5173/login
2.- iniciar sesión con un registro previo y marcar el recuadro de recuérdame 
3.- Iniciar sesion y luego cerrarla sesion
4.- cerrar sesion
![image](https://github.com/user-attachments/assets/e2abe0d1-26d6-48e9-a568-2aa29b71f092)
![image](https://github.com/user-attachments/assets/fa40ce8e-03f2-4111-8fa1-a5b87ad16795)
![image](https://github.com/user-attachments/assets/1679acd3-7a4c-45f8-88a0-6948401b36a6)
![image](https://github.com/user-attachments/assets/972475c1-a3e2-4913-94c8-bd69c14451c4)

**Comment by xXMamboxXx** [comment]
Analizando el funcionamiento de la pagina, de momento se decidió eliminar la función de "Recuerdame"
