### ISSUE TITLE
Restablecer contraseña 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#17]
Descripcion: Al momento de de enviar la verificacion de correo electronico para restablecer el correo electronico pasan 3 cosas, 1 se puede poner un correo que no esta registrado, 2 la contraseña ya no tiene medidas de seguridad, 3 al restablecer la contraseña aun asi con un correo existente este no se cambia.
Pasos
1.- Ingresar a la pagina principal http://localhost:5173/login
2.- hacer click en el apartado de olvidaste la contraseña
3.- Ingresar los datos correspondientes y verificar que no se cumplen con los requisitos
![image](https://github.com/user-attachments/assets/8be9c7f9-301f-4da4-84cd-e248dcf32496)
![image](https://github.com/user-attachments/assets/a67a12a5-5ebc-4efd-9409-922ea4d0caf1)
![image](https://github.com/user-attachments/assets/0c7eca5f-f733-4499-95ae-a05aa3033249)

**Comment by mirandaniel17** [comment]
![image](https://github.com/user-attachments/assets/6495520a-a381-4ae2-a7aa-52fa007c9102)
