### ISSUE TITLE
Editar las incripciones

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#18]
Descripciones: En el apartado de el registro de los estudiantes al momento de editar este nos redirique a un apartado de error 404 
Pasos: 
1.- Ingresar como usuario para registrar inscripciones 
2.- ir al apartado de inscripciones 
3.- Ingresar a la parte de editar inscripcion y aparecerá ese error 
![image](https://github.com/user-attachments/assets/c77fed3a-b832-4fce-9a5c-fa773d6d2e2a)
![image](https://github.com/user-attachments/assets/69b80f37-6212-48f5-9ba7-af565de96075)

**Comment by xXMamboxXx** [comment]
issue fixeado, revisar

![image](https://github.com/user-attachments/assets/2866d1a6-c52d-4ae4-bd9f-21853e048595)
