### ISSUE TITLE
Validacion de campo de Estudiantes

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#19]
Descripción: En el registro de estudiantes lo datos permiten poner numero en los nombres 
Pasos :
1.- iniciar sesión  en http://localhost:5173/
2.- ir al apartado de estudiantes
3.- Registrar estudiante http://localhost:5173/students

![image](https://github.com/user-attachments/assets/893e5a9b-f8cd-4785-a257-5b97e47e7fb3)
![image](https://github.com/user-attachments/assets/a3ae84f8-04c3-409c-b917-faf84640a107)

**Comment by mirandaniel17** [comment]
![image](https://github.com/user-attachments/assets/867776d8-42b7-4b2d-b08d-d8af216f19b1)
