### ISSUE TITLE
Validacion en campo docentes

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#20]
Descripción:  En la parte de nombre, apellidos este puede registrar los nombres con numeros y eso no tiene que ser posible
Pasos:
1.- Ingresar http://localhost:5173/teachers/create
2.- Ingresar los datos correspondientes 
![image](https://github.com/user-attachments/assets/e5e699e0-b235-4d53-83f1-a57fffdc71f1)
![image](https://github.com/user-attachments/assets/f7d36391-8d0b-40ac-bde4-d15a678b0fa4)

**Comment by xXMamboxXx** [comment]
Issue Fixeado(
1. no permite numero en nombre, apellido paterno y materno
2. no permite letras en numero
3. única excepción poner tilde 
)

![image](https://github.com/user-attachments/assets/90fc66f1-cc76-4f46-b2ad-eb1e97d65cab)
