### ISSUE TITLE
Seguridad en peligro

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#21]
Descripción: A momento del inicio de sesión este nos aclara en que lugar sea correo o contraseña es incorrecto
Pasos : 
1.-Ingresar a la pagina principal principal login: http://localhost:5173/login
2.-Ingresar credenciales correspondientes sea Gmail y contraseña

![image](https://github.com/user-attachments/assets/a0edc71b-2bb2-4e03-998f-f8eca760a38f)
![image](https://github.com/user-attachments/assets/b5eb33c2-105e-41fa-bba6-23d73ae908aa)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/fae2b5fc-ac18-4136-8d85-7524b3beb524)
