### ISSUE TITLE
Modificación del nombre al editar perfil

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#24]
Descripcion: Este nos muestra que al editar el perfil podemos poner numeros en el campo del nombre, asi este no tiene las validaciones correspondientes.
Pasos:
1.- ingresar al link ni inicio de sesion http://localhost:5173/login
2.-Ir al apartado de usuario 
3.- Editar la parte del nombre 
![image](https://github.com/user-attachments/assets/f0a94c43-d5a6-45bf-8a4d-e44a7c97fde1)
![image](https://github.com/user-attachments/assets/04dd884c-54f1-439f-9c45-9dac4ef68eaa)

**Comment by mirandaniel17** [comment]
![image](https://github.com/user-attachments/assets/befb10d0-62bd-4f1a-a984-39c2a7e8428d)
