### ISSUE TITLE
Cierre de inicio de sesion inesperado

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#25]
Descripcion: Al momento de iniciar sesion con las credenciales correspondientes, este nos muestra la pagina principal, el cual en la parte superios izquierda, al llevar el cursos del mouse y hacerle click este nos cierra la sesion de manera inesperada.
Pasos:
1.-Iniciar sesion en la direccion http://localhost:5173/login
2.- hacer click en el logo de la pagina en la parte superior derecha 

![image](https://github.com/user-attachments/assets/f987bbcd-eac8-4482-9bad-ef1ae520791d)
![image](https://github.com/user-attachments/assets/2cff7ef2-c117-47c7-8f2e-cb17824c996f)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/e5a6f903-b927-48c4-9438-a6c4f4696189)
