### ISSUE TITLE
Modulo Inscripciones

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#26]
Descripcion: En el apartado de l inscripcion al momento de el resgistro del estudiante por metodo de pagos, este no puede modificarse para registrar los pagos siguentes , en la segunda imagen tiene que hacer un apartado para regristar mas pagos en caso de que sea por cuotas.
Pasos:
1.- Ingresar como administrados a http://localhost:5173
2.-Ingresar al apartado de inscripcion y verificar la parte de a pagos o cuotas
3.- Registrar la inscripcion

![image](https://github.com/user-attachments/assets/391754cd-1b9f-4212-a6d8-5b1bb32c359a)
![image](https://github.com/user-attachments/assets/65c78e3c-8671-4ecd-b43b-8e868f20aa2b)

**Comment by mirandaniel17** [comment]
FIXEADO
![image](https://github.com/user-attachments/assets/8a5b7706-b4fe-4ea3-88ed-049fbdcc1ab8)
