### ISSUE TITLE
Modulo Tareas para notas 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#27]
Descripcion: Este modulo no cuenta con el apartado de modifcar la tarea para ser asignada al curso, al momento de crear la tarea esta no muestra un boton para poder ver la informacion, asi mismo despues de hacerle click este nos muestra los alumnos registrados y las notas para asignar
Pasos:
1.-Iniciar sesion como administrador http://localhost:5173
2.- Ir al apartado de tareas y registrar la tarea para el curso 
3.- Verificar la tarea y hacer click en el nombre
![image](https://github.com/user-attachments/assets/552f317d-49f4-4066-9b8c-1574040c5e8c)
![image](https://github.com/user-attachments/assets/5dd2d65a-32b7-439a-9c6f-3a40c189abb9)

**Comment by mirandaniel17** [comment]
FIXEADO
![Uploading image.png…]()
