### ISSUE TITLE
Notificacion de alerta de asistencia 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#28]
Descripcion: En el apartado correspondiente al momento de cerra la sesion este nos sigue mostrando la informacion de alerta aun asi saliendo de la sesion aparece el mensaje.
Pasos: 
1.- Ingresar a la pagina con credenciales correctas
2.- Registrar faltas para verificar la asistencia correspondiente
3.- cerrar sesion despues ver en la parte inferior derecha 
![image](https://github.com/user-attachments/assets/7072ed8c-07dd-486f-aec2-baf2a68ba530)

**Comment by mirandaniel17** [comment]
![image](https://github.com/user-attachments/assets/a2b366df-6738-4823-aede-fb69a7bbebec)
