### ISSUE TITLE
Modificacion de Inscripcion para pago

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#29]
Descripcion: En el caso de tener el pago correspondiente por pagos al contado este requiere que se añada un boton para futura modificacion en caso de el estudiante quiera pagar la mensualidad o pagar un monto de la misma.
Pasos:
1.- Ingresar como administrador 
2.-Ir al apartado de inscricion y registrar un estudiante con el pago a cuotas
3.- objservar que el mismo tiene un complejo de ausencia para modificaciones futuras
![image](https://github.com/user-attachments/assets/e610a126-4849-4b99-8220-2d33ecb487fd)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/ea2e0d82-f5bb-43b0-a299-91d3ec6b14b5)
