### ISSUE TITLE
Buscador de estudiantes para inscribir

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#30]
descripción: al momento de inscribir a un estudiante este en el combo box solo me muestras 10 datos de estudiantes, de los 700 estudiantes previamente registrados 
pasos: 
1.- Ingresar como administrador a la pagina 
2.-Ingresar al apartado de inscribir nuevo estudiante
3.- hacer click en el combo box para verificar informacion o buscarlo por nombre
![image](https://github.com/user-attachments/assets/33a5c755-528f-4e08-8d50-5a8d25d7b954)

**Comment by xXMamboxXx** [comment]
issue fixeado 
ya muestra el total de datos (EN REVISION)
![image](https://github.com/user-attachments/assets/8b0c8083-dce1-44ed-9e2f-d6345b1c30e7)
