### ISSUE TITLE
Informacion de tareas nuevas

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#31]
Descripcion: En el momento de registrar la nueva tarea para las calificaciones futuras este muestra poca información intuitiva para el uso del mismo 
pasos:
1.-Ingresar como administrados
2.-Realizar una tarea correspondientes a un curso con su docente asignado 
3.-Verificar que se necesita botones para que el usuarioa sepa que se hara 
![image](https://github.com/user-attachments/assets/34dda325-e612-43b6-bd41-9a7abed8dde2)
![image](https://github.com/user-attachments/assets/5bab52f5-8541-48dd-923b-1ef4e2f3abdf)

**Comment by mirandaniel17** [comment]
FIXEADO
![image](https://github.com/user-attachments/assets/1b450623-a112-4ef0-8991-50969d71d275)
