### ISSUE TITLE
Busqueda de registro de pago 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#32]
Descripcion: Al momento de hacer una busqueda para ingresar el pago correspondiente este no encuentra el dato asignado a buscar
Pasos:
1.- Ingresar como administrador http://localhost:5173/login
2.-Ir al apartado de pagos correspondientes 
3.- En el apartado de seleccionar estudiante este solo muestra una lista de 10 estudiantes

![image](https://github.com/user-attachments/assets/f9e9d972-e22f-438b-b0d4-4ff1c6c52d7b)

**Comment by xXMamboxXx** [comment]
issue fixeado, revisas

![image](https://github.com/user-attachments/assets/7e2d1bd8-6d50-41df-8a57-94a1ddfda79b)
