### ISSUE TITLE
Pestaña de docentes- VALIDACION DEL CAMPO - ESPECIALIDAD

### ISSUE THREAD

**Issue by chavezfl** [mirandaniel17/itc-backend#4]
En este campo se debe asignar un mensaje de error o advertencia de que no se podra teclear numeracion o caracteres especiales. 
![Rep1](https://github.com/user-attachments/assets/38301b55-5b05-451a-98a9-00c8905b871c)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/73c4fdc7-60e4-429c-98d4-b06162d6e7a0)
