### ISSUE TITLE
VALIDACIONES - MODULO DE DOCENTES - AGREGAR

### ISSUE THREAD

**Issue by chavezfl** [mirandaniel17/itc-backend#5]
En el modulo de docentes al crear un docente en el campo de CI
1: Como el instituto acepta desde los 13 años hacia adelante, y no tiene un limite de edad este campo debe aceptar idigitos de 6.
2:Debe reconocer tambien CI extranjeros(no nacidos en el pais), que quieran enseñar en el instituto
![image](https://github.com/user-attachments/assets/40bb0dcb-08df-4382-a016-7d2b86b38afa)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/a379205a-d749-4a30-8ac0-b99f32a32638)
