### ISSUE TITLE
AUSENCIA DE INFORMACION

### ISSUE THREAD

**Issue by xXMamboxXx** [mirandaniel17/itc-backend#6]
Tipo= Error 
Descripción= Error 404
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de horarios: http://localhost:5173/schedules/set-schedule
3.-Guardar horario
![Captura de pantalla 2024-11-06 211251](https://github.com/user-attachments/assets/75392583-05bd-4e4e-83cd-b2639e0a2217)
![Captura de pantalla 2024-11-06 211306](https://github.com/user-attachments/assets/fcd0decb-2ae5-44f8-a8e6-812e410688df)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/4ad9c94f-ab32-4697-ae4d-d16678566525)
