### ISSUE TITLE
Validación de campos Turnos

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#7]
Tipo= Error, mejora
Descripción= En los campos de creacion de Nombre de turno este se puede agregar letras cosa que no es valido
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de turnos link: http://localhost:5173/shifts/create
3.-Creacion de datos Turno con letras no permitirlo
4.-Creacion de turno con los datos no permitidos al momento de crear

![image](https://github.com/user-attachments/assets/90826bbd-5a6a-4f1e-9c59-686a71319e7e)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/752baa21-4cd8-4c69-baa8-b4408fba002b)
10 DE NOVIEMBRE DE 2024
