### ISSUE TITLE
Validacion de campos de hora 

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#8]
Tipo= Error, mejora
Descripción= La hora inicial no puede ser igual a la hora final, tiene que haber una diferencia de por lo menos 1 hora de acuerdo a este, para mejorar los datos
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de turnos link: http://localhost:5173/shifts
3.-Click en nuevo para crear turno link: http://localhost:5173/shifts/create
4.-Ponga las horas iguales de acuerdo a esto no se alerta 

![image](https://github.com/user-attachments/assets/c802640c-12d5-4b8b-a4f5-8ce0a8b7cefd)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/ec13c0ac-c805-4e3e-b31f-c6a5c66fc695)
10 DE NOVIEMBRE DE 2024
