### ISSUE TITLE
Validacion de hora en Turno

### ISSUE THREAD

**Issue by AleSanRu** [mirandaniel17/itc-backend#9]
Tipo= Error, mejora, 
Descripción= Al momento de ingresar las horas la hora final no puede ser inferior a la inicial, ya que con esto lleva a errores de informacion
1.-Ingreso al login de inicio link: http: //localhost:5173/login
2.-Click en el apartado de turnos link: http://localhost:5173/shifts
3.-Click en nuevo para crear turno link: http://localhost:5173/shifts/create
4.-Horas asignadas de manera incorrecta en los campos, hora inicio, hora fin

![image](https://github.com/user-attachments/assets/3a7d40af-52c8-4de4-91b1-0c0b0c87d591)

**Comment by mirandaniel17** [comment]
ISSUE FIXEADO
![image](https://github.com/user-attachments/assets/bfbca649-e57b-449a-b8ed-767dad335aff)
10 DE NOVIEMBRE DE 2024
